language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
sudo: required
group: deprecated-2017Q2
before_install:
  - curl -o ~/pilosa-server https://storage.googleapis.com/pilosa/pilosa-sumreduce && chmod +x ~/pilosa-server
  - ~/pilosa-server server &
  - sleep 5
install: "pip install -r requirements.txt -r test-requirements.txt coveralls"
script: make cover
after_success:
  coveralls

