language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"
  - "pypy-5.3.1"
install: "pip install -r requirements.txt -r test-requirements.txt"
script: make test
